// src/components/RoutesTable.tsx
import { useState } from 'react'
import type { Route } from '../models/netprobe.models'

export default function RoutesTable({ routes }: { routes: Route[] }) {
  const [filter, setFilter] = useState('')

  const filtered = filter ? routes.filter(r => r.routeType === filter) : routes
  const types = Array.from(new Set(routes.map(r => r.routeType)))

  return (
    <div>
      {types.length > 0 && (
        <div className="flex gap-2 mb-4 flex-wrap">
          <button
            onClick={() => setFilter('')}
            className={`px-3 py-1 rounded-lg text-xs font-medium transition ${filter === '' ? 'bg-blue-600 text-white' : 'bg-gray-700 text-gray-300 hover:bg-gray-600'}`}
          >
            Todos
          </button>
          {types.map(t => (
            <button
              key={t}
              onClick={() => setFilter(t)}
              className={`px-3 py-1 rounded-lg text-xs font-medium transition ${filter === t ? 'bg-blue-600 text-white' : 'bg-gray-700 text-gray-300 hover:bg-gray-600'}`}
            >
              {t}
            </button>
          ))}
        </div>
      )}
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="text-left text-gray-400 border-b border-gray-700">
              <th className="py-3 pr-4">Destino</th>
              <th className="py-3 pr-4">Gateway</th>
              <th className="py-3 pr-4">Interface</th>
              <th className="py-3 pr-4">Tipo</th>
              <th className="py-3 pr-4">Distância</th>
              <th className="py-3 pr-4">Status</th>
            </tr>
          </thead>
          <tbody>
            {filtered.map((r, i) => (
              <tr key={i} className="border-b border-gray-800 hover:bg-gray-700/40 transition">
                <td className="py-3 pr-4 font-mono text-white text-xs">{r.dstAddress}</td>
                <td className="py-3 pr-4 font-mono text-gray-300 text-xs">{r.gateway || '—'}</td>
                <td className="py-3 pr-4 text-gray-300">{r.interface}</td>
                <td className="py-3 pr-4 text-gray-400 text-xs">{r.routeType}</td>
                <td className="py-3 pr-4 text-gray-300">{r.distance}</td>
                <td className="py-3 pr-4">
                  <span className={`px-2 py-0.5 rounded text-xs font-medium ${r.active ? 'bg-green-900 text-green-300' : 'bg-gray-700 text-gray-400'}`}>
                    {r.active ? 'ativo' : 'inativo'}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        {filtered.length === 0 && (
          <p className="text-gray-500 text-sm py-6 text-center">Nenhuma rota encontrada</p>
        )}
      </div>
    </div>
  )
}

// src/app/components/routes-table/routes-table.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Route } from '../../models/netprobe.models';

@Component({
  selector: 'app-routes-table',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './routes-table.component.html'
})
export class RoutesTableComponent {
  @Input() routes: Route[] = [];
  filter = 'all';

  get filtered(): Route[] {
    if (this.filter === 'all') return this.routes;
    return this.routes.filter(r => r.routeType?.toLowerCase() === this.filter);
  }

  get types(): string[] {
    const t = new Set(this.routes.map(r => r.routeType?.toLowerCase()).filter(Boolean));
    return ['all', ...Array.from(t)];
  }
}

<div class="space-y-4">
  <div class="flex gap-2 flex-wrap">
    <button *ngFor="let t of types" (click)="filter = t"
      [class]="filter === t ? 'bg-blue-600 text-white' : 'bg-gray-700 text-gray-300 hover:bg-gray-600'"
      class="px-3 py-1 rounded text-xs font-medium transition capitalize">
      {{ t }}
    </button>
  </div>
  <div class="overflow-x-auto">
    <table class="w-full text-sm">
      <thead>
        <tr class="text-left text-gray-400 border-b border-gray-700">
          <th class="py-3 pr-4">Destino</th>
          <th class="py-3 pr-4">Gateway</th>
          <th class="py-3 pr-4">Interface</th>
          <th class="py-3 pr-4">Tipo</th>
          <th class="py-3 pr-4">Dist.</th>
          <th class="py-3 pr-4">Status</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let r of filtered" class="border-b border-gray-800 hover:bg-gray-700/40 transition">
          <td class="py-3 pr-4 font-mono text-white">{{ r.dstAddress }}</td>
          <td class="py-3 pr-4 font-mono text-gray-300">{{ r.gateway || '—' }}</td>
          <td class="py-3 pr-4 text-gray-300">{{ r.interface }}</td>
          <td class="py-3 pr-4 text-xs text-gray-400 uppercase">{{ r.routeType }}</td>
          <td class="py-3 pr-4 text-gray-400">{{ r.distance }}</td>
          <td class="py-3 pr-4">
            <span [class]="r.active ? 'bg-green-900 text-green-300' : 'bg-red-900 text-red-300'"
              class="px-2 py-0.5 rounded text-xs font-medium">
              {{ r.active ? 'active' : 'inactive' }}
            </span>
          </td>
        </tr>
      </tbody>
    </table>
    <p *ngIf="filtered.length === 0" class="text-gray-500 text-sm py-6 text-center">Nenhuma rota encontrada</p>
  </div>
</div>
