// src/components/LogsViewer.tsx
import { useState } from 'react'
import type { LogEntry } from '../models/netprobe.models'

export default function LogsViewer({ logs }: { logs: LogEntry[] }) {
  const [filter, setFilter] = useState('')

  const topics = Array.from(new Set(logs.map(l => l.topics).filter(Boolean)))
  const filtered = filter ? logs.filter(l => l.topics === filter) : logs

  return (
    <div>
      {topics.length > 0 && (
        <div className="flex gap-2 mb-4 flex-wrap">
          <button
            onClick={() => setFilter('')}
            className={`px-3 py-1 rounded-lg text-xs font-medium transition ${filter === '' ? 'bg-blue-600 text-white' : 'bg-gray-700 text-gray-300 hover:bg-gray-600'}`}
          >
            Todos
          </button>
          {topics.map(t => (
            <button
              key={t}
              onClick={() => setFilter(t)}
              className={`px-3 py-1 rounded-lg text-xs font-medium transition ${filter === t ? 'bg-blue-600 text-white' : 'bg-gray-700 text-gray-300 hover:bg-gray-600'}`}
            >
              {t}
            </button>
          ))}
        </div>
      )}
      <div className="space-y-1 max-h-[60vh] overflow-y-auto">
        {filtered.map((log, i) => (
          <div key={i} className="flex gap-3 text-xs font-mono bg-gray-900 px-3 py-2 rounded">
            <span className="text-gray-500 shrink-0">{log.time}</span>
            <span className="text-blue-400 shrink-0">[{log.topics}]</span>
            <span className="text-gray-200">{log.message}</span>
          </div>
        ))}
        {filtered.length === 0 && (
          <p className="text-gray-500 text-sm py-6 text-center">Nenhum log encontrado</p>
        )}
      </div>
    </div>
  )
}

// src/app/components/logs-viewer/logs-viewer.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { LogEntry } from '../../models/netprobe.models';

@Component({
  selector: 'app-logs-viewer',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './logs-viewer.component.html'
})
export class LogsViewerComponent {
  @Input() logs: LogEntry[] = [];
  topicFilter = 'all';

  get topics(): string[] {
    const t = new Set(this.logs.map(l => l.topics).filter(Boolean));
    return ['all', ...Array.from(t)];
  }

  get filtered(): LogEntry[] {
    if (this.topicFilter === 'all') return this.logs;
    return this.logs.filter(l => l.topics === this.topicFilter);
  }
}

<div class="space-y-3">
  <div class="flex gap-2 flex-wrap">
    <button *ngFor="let t of topics" (click)="topicFilter = t"
      [class]="topicFilter === t ? 'bg-blue-600 text-white' : 'bg-gray-700 text-gray-300 hover:bg-gray-600'"
      class="px-3 py-1 rounded text-xs font-medium transition">{{ t }}</button>
  </div>
  <div class="space-y-1 max-h-[480px] overflow-y-auto">
    <div *ngFor="let log of filtered"
      class="flex gap-3 text-xs font-mono py-2 px-3 rounded bg-gray-800/60 border border-gray-700/50 hover:bg-gray-700/40">
      <span class="text-gray-500 shrink-0 w-20">{{ log.time }}</span>
      <span class="text-blue-400 shrink-0 w-24 truncate">{{ log.topics }}</span>
      <span class="text-gray-200">{{ log.message }}</span>
    </div>
    <p *ngIf="filtered.length === 0" class="text-gray-500 text-sm py-6 text-center">Nenhum log encontrado</p>
  </div>
</div>
