// src/app/components/dashboard/dashboard.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Subscription } from 'rxjs';
import { MikrotikService } from '../../services/mikrotik.service';
import { MikrotikData, ConnectionRequest, ChartPoint } from '../../models/netprobe.models';
import { SystemResourcesComponent } from '../system-resources/system-resources.component';
import { InterfacesTableComponent } from '../interfaces-table/interfaces-table.component';
import { RoutesTableComponent } from '../routes-table/routes-table.component';
import { ArpTableComponent } from '../arp-table/arp-table.component';
import { DhcpTableComponent } from '../dhcp-table/dhcp-table.component';
import { LogsViewerComponent } from '../logs-viewer/logs-viewer.component';
import { DiagnosticPanelComponent } from '../diagnostic-panel/diagnostic-panel.component';

type Tab = 'overview' | 'interfaces' | 'routes' | 'arp' | 'dhcp' | 'logs' | 'diagnostic';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [
    CommonModule,
    SystemResourcesComponent,
    InterfacesTableComponent,
    RoutesTableComponent,
    ArpTableComponent,
    DhcpTableComponent,
    LogsViewerComponent,
    DiagnosticPanelComponent
  ],
  templateUrl: './dashboard.component.html'
})
export class DashboardComponent implements OnInit, OnDestroy {
  activeTab: Tab = 'overview';
  data: MikrotikData | null = null;
  loading = false;
  lastUpdate: Date | null = null;
  countdown = 60;
  cpuHistory: ChartPoint[] = [];
  ramHistory: ChartPoint[] = [];
  credentials: ConnectionRequest | null = null;

  private subs = new Subscription();

  readonly tabs: { id: Tab; label: string }[] = [
    { id: 'overview', label: 'Visão Geral' },
    { id: 'interfaces', label: 'Interfaces' },
    { id: 'routes', label: 'Rotas' },
    { id: 'arp', label: 'ARP' },
    { id: 'dhcp', label: 'DHCP' },
    { id: 'logs', label: 'Logs' },
    { id: 'diagnostic', label: 'Diagnóstico' }
  ];

  constructor(public mikrotik: MikrotikService) {}

  ngOnInit(): void {
    this.subs.add(this.mikrotik.data$.subscribe(d => this.data = d));
    this.subs.add(this.mikrotik.loading$.subscribe(l => this.loading = l));
    this.subs.add(this.mikrotik.lastUpdate$.subscribe(t => this.lastUpdate = t));
    this.subs.add(this.mikrotik.countdown$.subscribe(c => this.countdown = c));
    this.subs.add(this.mikrotik.cpuHistory$.subscribe(h => this.cpuHistory = h));
    this.subs.add(this.mikrotik.ramHistory$.subscribe(h => this.ramHistory = h));
    // snapshot credentials via service (we stored them there)
    this.subs.add(this.mikrotik.connected$.subscribe(() => {
      // credentials are accessible through service internals exposed below
    }));
  }

  get creds(): ConnectionRequest {
    return (this.mikrotik as any).credentials ?? { ip: '', username: '', password: '' };
  }

  disconnect(): void { this.mikrotik.disconnect(); }
  refresh(): void { this.mikrotik.refresh(); }

  formatTime(d: Date): string {
    return d.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit', second: '2-digit' });
  }

  get countdownWidth(): string {
    return Math.round((this.countdown / 60) * 100) + '%';
  }

  ngOnDestroy(): void { this.subs.unsubscribe(); }
}

<div class="min-h-screen bg-gray-900 flex flex-col" *ngIf="data">

  <!-- Header fixo -->
  <header class="bg-gray-800 border-b border-gray-700 px-6 py-3 flex items-center justify-between gap-4 flex-wrap sticky top-0 z-10">
    <div class="flex items-center gap-4">
      <span class="text-white font-bold text-lg">{{ data.systemResource.identity || 'MikroTik' }}</span>
      <span class="text-xs text-gray-400 font-mono bg-gray-900 px-2 py-1 rounded">{{ creds.ip }}</span>
      <span class="text-xs text-gray-400">RouterOS {{ data.systemResource.routerOsVersion }}</span>
    </div>
    <div class="flex items-center gap-3 flex-wrap">
      <!-- Countdown -->
      <div class="flex items-center gap-2">
        <div class="w-28 h-1.5 bg-gray-700 rounded-full overflow-hidden">
          <div class="h-full bg-blue-500 transition-all duration-1000 rounded-full" [style.width]="countdownWidth"></div>
        </div>
        <span class="text-xs text-gray-400 tabular-nums">{{ countdown }}s</span>
      </div>
      <!-- Last update -->
      <span *ngIf="lastUpdate" class="text-xs text-gray-500">
        Atualizado: {{ formatTime(lastUpdate) }}
      </span>
      <!-- Loading indicator -->
      <svg *ngIf="loading" class="animate-spin h-4 w-4 text-blue-400" fill="none" viewBox="0 0 24 24">
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/>
        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z"/>
      </svg>
      <button (click)="refresh()" [disabled]="loading"
        class="bg-gray-700 hover:bg-gray-600 disabled:opacity-50 text-gray-200 text-xs px-3 py-1.5 rounded-lg transition">
        Atualizar agora
      </button>
      <button (click)="disconnect()"
        class="bg-red-800/60 hover:bg-red-700 text-red-300 text-xs px-3 py-1.5 rounded-lg transition">
        Desconectar
      </button>
    </div>
  </header>

  <!-- Abas -->
  <nav class="bg-gray-800 border-b border-gray-700 px-6 flex gap-1 overflow-x-auto">
    <button *ngFor="let tab of tabs" (click)="activeTab = tab.id"
      [class]="activeTab === tab.id
        ? 'border-b-2 border-blue-500 text-blue-400'
        : 'text-gray-400 hover:text-gray-200 border-b-2 border-transparent'"
      class="px-4 py-3 text-sm font-medium whitespace-nowrap transition">
      {{ tab.label }}
    </button>
  </nav>

  <!-- Conteúdo -->
  <main class="flex-1 p-6">

    <ng-container [ngSwitch]="activeTab">

      <!-- Visão Geral -->
      <ng-container *ngSwitchCase="'overview'">
        <app-system-resources
          [resource]="data.systemResource"
          [cpuHistory]="cpuHistory"
          [ramHistory]="ramHistory">
        </app-system-resources>
      </ng-container>

      <!-- Interfaces -->
      <ng-container *ngSwitchCase="'interfaces'">
        <div class="bg-gray-800 border border-gray-700 rounded-xl p-5">
          <h2 class="text-gray-200 font-semibold mb-4">Interfaces de rede</h2>
          <app-interfaces-table [interfaces]="data.interfaces"></app-interfaces-table>
        </div>
      </ng-container>

      <!-- Rotas -->
      <ng-container *ngSwitchCase="'routes'">
        <div class="bg-gray-800 border border-gray-700 rounded-xl p-5">
          <h2 class="text-gray-200 font-semibold mb-4">Tabela de rotas</h2>
          <app-routes-table [routes]="data.routes"></app-routes-table>
        </div>
      </ng-container>

      <!-- ARP -->
      <ng-container *ngSwitchCase="'arp'">
        <div class="bg-gray-800 border border-gray-700 rounded-xl p-5">
          <h2 class="text-gray-200 font-semibold mb-4">Tabela ARP</h2>
          <app-arp-table [entries]="data.arpEntries"></app-arp-table>
        </div>
      </ng-container>

      <!-- DHCP -->
      <ng-container *ngSwitchCase="'dhcp'">
        <div class="bg-gray-800 border border-gray-700 rounded-xl p-5">
          <h2 class="text-gray-200 font-semibold mb-4">DHCP Leases</h2>
          <app-dhcp-table [leases]="data.dhcpLeases"></app-dhcp-table>
        </div>
      </ng-container>

      <!-- Logs -->
      <ng-container *ngSwitchCase="'logs'">
        <div class="bg-gray-800 border border-gray-700 rounded-xl p-5">
          <h2 class="text-gray-200 font-semibold mb-4">Logs do sistema</h2>
          <app-logs-viewer [logs]="data.logs"></app-logs-viewer>
        </div>
      </ng-container>

      <!-- Diagnóstico -->
      <ng-container *ngSwitchCase="'diagnostic'">
        <app-diagnostic-panel [credentials]="creds"></app-diagnostic-panel>
      </ng-container>

    </ng-container>
  </main>

</div>

// src/components/Dashboard.tsx
import { useState } from 'react'
import { useMikrotik } from '../store/mikrotik.store'
import SystemResources from './SystemResources'
import InterfacesTable from './InterfacesTable'
import RoutesTable from './RoutesTable'
import ArpTable from './ArpTable'
import DhcpTable from './DhcpTable'
import LogsViewer from './LogsViewer'
import DiagnosticPanel from './DiagnosticPanel'

type Tab = 'overview' | 'interfaces' | 'routes' | 'arp' | 'dhcp' | 'logs' | 'diagnostic'

const TABS: { id: Tab; label: string }[] = [
  { id: 'overview', label: 'Visão Geral' },
  { id: 'interfaces', label: 'Interfaces' },
  { id: 'routes', label: 'Rotas' },
  { id: 'arp', label: 'ARP' },
  { id: 'dhcp', label: 'DHCP' },
  { id: 'logs', label: 'Logs' },
  { id: 'diagnostic', label: 'Diagnóstico' },
]

const Spinner = () => (
  <svg className="animate-spin h-4 w-4 text-blue-400" fill="none" viewBox="0 0 24 24">
    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z" />
  </svg>
)

export default function Dashboard() {
  const { data, loading, lastUpdate, countdown, cpuHistory, ramHistory, credentials, disconnect, refresh } = useMikrotik()
  const [activeTab, setActiveTab] = useState<Tab>('overview')

  if (!data || !credentials) return null

  const countdownWidth = Math.round((countdown / 60) * 100) + '%'
  const formatTime = (d: Date) => d.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit', second: '2-digit' })

  return (
    <div className="min-h-screen bg-gray-900 flex flex-col">

      <header className="bg-gray-800 border-b border-gray-700 px-6 py-3 flex items-center justify-between gap-4 flex-wrap sticky top-0 z-10">
        <div className="flex items-center gap-4">
          <span className="text-white font-bold text-lg">{data.systemResource.identity || 'MikroTik'}</span>
          <span className="text-xs text-gray-400 font-mono bg-gray-900 px-2 py-1 rounded">{credentials.ip}</span>
          <span className="text-xs text-gray-400">RouterOS {data.systemResource.routerOsVersion}</span>
        </div>
        <div className="flex items-center gap-3 flex-wrap">
          <div className="flex items-center gap-2">
            <div className="w-28 h-1.5 bg-gray-700 rounded-full overflow-hidden">
              <div className="h-full bg-blue-500 transition-all duration-1000 rounded-full" style={{ width: countdownWidth }} />
            </div>
            <span className="text-xs text-gray-400 tabular-nums">{countdown}s</span>
          </div>
          {lastUpdate && (
            <span className="text-xs text-gray-500">Atualizado: {formatTime(lastUpdate)}</span>
          )}
          {loading && <Spinner />}
          <button onClick={refresh} disabled={loading}
            className="bg-gray-700 hover:bg-gray-600 disabled:opacity-50 text-gray-200 text-xs px-3 py-1.5 rounded-lg transition">
            Atualizar agora
          </button>
          <button onClick={disconnect}
            className="bg-red-800/60 hover:bg-red-700 text-red-300 text-xs px-3 py-1.5 rounded-lg transition">
            Desconectar
          </button>
        </div>
      </header>

      <nav className="bg-gray-800 border-b border-gray-700 px-6 flex gap-1 overflow-x-auto">
        {TABS.map(tab => (
          <button key={tab.id} onClick={() => setActiveTab(tab.id)}
            className={`px-4 py-3 text-sm font-medium whitespace-nowrap transition border-b-2 ${
              activeTab === tab.id
                ? 'border-blue-500 text-blue-400'
                : 'border-transparent text-gray-400 hover:text-gray-200'
            }`}>
            {tab.label}
          </button>
        ))}
      </nav>

      <main className="flex-1 p-6">
        {activeTab === 'overview' && (
          <SystemResources resource={data.systemResource} cpuHistory={cpuHistory} ramHistory={ramHistory} />
        )}
        {activeTab === 'interfaces' && (
          <div className="bg-gray-800 border border-gray-700 rounded-xl p-5">
            <h2 className="text-gray-200 font-semibold mb-4">Interfaces de rede</h2>
            <InterfacesTable interfaces={data.interfaces} />
          </div>
        )}
        {activeTab === 'routes' && (
          <div className="bg-gray-800 border border-gray-700 rounded-xl p-5">
            <h2 className="text-gray-200 font-semibold mb-4">Tabela de rotas</h2>
            <RoutesTable routes={data.routes} />
          </div>
        )}
        {activeTab === 'arp' && (
          <div className="bg-gray-800 border border-gray-700 rounded-xl p-5">
            <h2 className="text-gray-200 font-semibold mb-4">Tabela ARP</h2>
            <ArpTable entries={data.arpEntries} />
          </div>
        )}
        {activeTab === 'dhcp' && (
          <div className="bg-gray-800 border border-gray-700 rounded-xl p-5">
            <h2 className="text-gray-200 font-semibold mb-4">DHCP Leases</h2>
            <DhcpTable leases={data.dhcpLeases} />
          </div>
        )}
        {activeTab === 'logs' && (
          <div className="bg-gray-800 border border-gray-700 rounded-xl p-5">
            <h2 className="text-gray-200 font-semibold mb-4">Logs do sistema</h2>
            <LogsViewer logs={data.logs} />
          </div>
        )}
        {activeTab === 'diagnostic' && (
          <DiagnosticPanel credentials={credentials} />
        )}
      </main>
    </div>
  )
}
