// src/app/components/interfaces-table/interfaces-table.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NetworkInterface } from '../../models/netprobe.models';

@Component({
  selector: 'app-interfaces-table',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './interfaces-table.component.html'
})
export class InterfacesTableComponent {
  @Input() interfaces: NetworkInterface[] = [];

  formatBytes(bytes: number): string {
    if (bytes >= 1_073_741_824) return (bytes / 1_073_741_824).toFixed(2) + ' GB';
    if (bytes >= 1_048_576) return (bytes / 1_048_576).toFixed(2) + ' MB';
    if (bytes >= 1024) return (bytes / 1024).toFixed(2) + ' KB';
    return bytes + ' B';
  }
}

<div class="overflow-x-auto">
  <table class="w-full text-sm">
    <thead>
      <tr class="text-left text-gray-400 border-b border-gray-700">
        <th class="py-3 pr-4">Nome</th>
        <th class="py-3 pr-4">Tipo</th>
        <th class="py-3 pr-4">Status</th>
        <th class="py-3 pr-4">MAC</th>
        <th class="py-3 pr-4">MTU</th>
        <th class="py-3 pr-4">RX</th>
        <th class="py-3 pr-4">TX</th>
        <th class="py-3 pr-4">Erros RX/TX</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let iface of interfaces" class="border-b border-gray-800 hover:bg-gray-700/40 transition">
        <td class="py-3 pr-4 font-mono text-white">{{ iface.name }}</td>
        <td class="py-3 pr-4 text-gray-300">{{ iface.type }}</td>
        <td class="py-3 pr-4">
          <span [class]="iface.running ? 'bg-green-900 text-green-300' : 'bg-red-900 text-red-300'"
            class="px-2 py-0.5 rounded text-xs font-medium">
            {{ iface.running ? 'up' : 'down' }}
          </span>
        </td>
        <td class="py-3 pr-4 font-mono text-gray-300 text-xs">{{ iface.macAddress }}</td>
        <td class="py-3 pr-4 text-gray-300">{{ iface.mtu }}</td>
        <td class="py-3 pr-4 text-gray-300">{{ formatBytes(iface.rxBytes) }}</td>
        <td class="py-3 pr-4 text-gray-300">{{ formatBytes(iface.txBytes) }}</td>
        <td class="py-3 pr-4 text-gray-400 text-xs">{{ iface.rxErrors }} / {{ iface.txErrors }}</td>
      </tr>
    </tbody>
  </table>
  <p *ngIf="interfaces.length === 0" class="text-gray-500 text-sm py-6 text-center">Nenhuma interface encontrada</p>
</div>

// src/components/InterfacesTable.tsx
import type { NetworkInterface } from '../models/netprobe.models'

function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 B'
  const k = 1024
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${sizes[i]}`
}

export default function InterfacesTable({ interfaces }: { interfaces: NetworkInterface[] }) {
  return (
    <div className="overflow-x-auto">
      <table className="w-full text-sm">
        <thead>
          <tr className="text-left text-gray-400 border-b border-gray-700">
            <th className="py-3 pr-4">Nome</th>
            <th className="py-3 pr-4">Tipo</th>
            <th className="py-3 pr-4">Status</th>
            <th className="py-3 pr-4">MAC</th>
            <th className="py-3 pr-4">MTU</th>
            <th className="py-3 pr-4">RX</th>
            <th className="py-3 pr-4">TX</th>
            <th className="py-3 pr-4">Erros RX/TX</th>
          </tr>
        </thead>
        <tbody>
          {interfaces.map(iface => (
            <tr key={iface.name} className="border-b border-gray-800 hover:bg-gray-700/40 transition">
              <td className="py-3 pr-4 font-mono text-white">{iface.name}</td>
              <td className="py-3 pr-4 text-gray-300">{iface.type}</td>
              <td className="py-3 pr-4">
                <span className={`px-2 py-0.5 rounded text-xs font-medium ${iface.running ? 'bg-green-900 text-green-300' : 'bg-red-900 text-red-300'}`}>
                  {iface.running ? 'up' : 'down'}
                </span>
              </td>
              <td className="py-3 pr-4 font-mono text-gray-300 text-xs">{iface.macAddress}</td>
              <td className="py-3 pr-4 text-gray-300">{iface.mtu}</td>
              <td className="py-3 pr-4 text-gray-300">{formatBytes(iface.rxBytes)}</td>
              <td className="py-3 pr-4 text-gray-300">{formatBytes(iface.txBytes)}</td>
              <td className="py-3 pr-4 text-gray-400 text-xs">{iface.rxErrors} / {iface.txErrors}</td>
            </tr>
          ))}
        </tbody>
      </table>
      {interfaces.length === 0 && (
        <p className="text-gray-500 text-sm py-6 text-center">Nenhuma interface encontrada</p>
      )}
    </div>
  )
}
