// src/components/SystemResources.tsx
import {
  Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement,
  Tooltip, Filler,
} from 'chart.js'
import { Line } from 'react-chartjs-2'
import type { SystemResource, ChartPoint } from '../models/netprobe.models'

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Tooltip, Filler)

const chartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  animation: { duration: 300 },
  plugins: { legend: { display: false }, tooltip: { mode: 'index' as const, intersect: false } },
  scales: {
    x: { ticks: { color: '#6b7280', font: { size: 10 } }, grid: { color: '#374151' } },
    y: { ticks: { color: '#6b7280', font: { size: 10 } }, grid: { color: '#374151' }, beginAtZero: true },
  },
}

function makeChartData(points: ChartPoint[], color: string) {
  return {
    labels: points.map(p => p.timestamp),
    datasets: [{
      data: points.map(p => p.value),
      borderColor: color,
      backgroundColor: color.replace(')', ', 0.1)').replace('rgb', 'rgba'),
      fill: true,
      tension: 0.3,
      pointRadius: 2,
    }],
  }
}

interface Props {
  resource: SystemResource
  cpuHistory: ChartPoint[]
  ramHistory: ChartPoint[]
}

export default function SystemResources({ resource, cpuHistory, ramHistory }: Props) {
  const usedMemMB = Math.round(resource.totalMemory - resource.freeMemory)
  const ramPercent = resource.totalMemory > 0 ? Math.round((usedMemMB / resource.totalMemory) * 100) : 0
  const usedDiskMB = Math.round(resource.totalDisk - resource.freeDisk)

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-gray-800 border border-gray-700 rounded-xl p-5">
          <p className="text-xs text-gray-400 uppercase tracking-wide">CPU</p>
          <p className="text-3xl font-bold text-blue-400 mt-1">{resource.cpuLoad}<span className="text-lg text-gray-400">%</span></p>
        </div>
        <div className="bg-gray-800 border border-gray-700 rounded-xl p-5">
          <p className="text-xs text-gray-400 uppercase tracking-wide">RAM usada</p>
          <p className="text-3xl font-bold text-purple-400 mt-1">{usedMemMB}<span className="text-lg text-gray-400"> MB</span></p>
          <p className="text-xs text-gray-500 mt-1">{ramPercent}% de {resource.totalMemory.toLocaleString('pt-BR')} MB</p>
        </div>
        <div className="bg-gray-800 border border-gray-700 rounded-xl p-5">
          <p className="text-xs text-gray-400 uppercase tracking-wide">Disco usado</p>
          <p className="text-2xl font-bold text-emerald-400 mt-1">{usedDiskMB}<span className="text-base text-gray-400"> MB</span></p>
          <p className="text-xs text-gray-500 mt-1">livre: {resource.freeDisk.toLocaleString('pt-BR')} MB</p>
        </div>
        <div className="bg-gray-800 border border-gray-700 rounded-xl p-5">
          <p className="text-xs text-gray-400 uppercase tracking-wide">Uptime</p>
          <p className="text-lg font-semibold text-white mt-1 break-all">{resource.uptime}</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <div className="bg-gray-800 border border-gray-700 rounded-xl p-5">
          <p className="text-sm text-gray-400 mb-3">CPU (%) — últimos 30 pontos</p>
          <div className="h-48">
            <Line data={makeChartData(cpuHistory, 'rgb(96, 165, 250)')} options={chartOptions} />
          </div>
        </div>
        <div className="bg-gray-800 border border-gray-700 rounded-xl p-5">
          <p className="text-sm text-gray-400 mb-3">RAM (MB) — últimos 30 pontos</p>
          <div className="h-48">
            <Line data={makeChartData(ramHistory, 'rgb(167, 139, 250)')} options={chartOptions} />
          </div>
        </div>
      </div>

      <div className="bg-gray-800 border border-gray-700 rounded-xl p-5 grid grid-cols-2 lg:grid-cols-3 gap-4 text-sm">
        <div><span className="text-gray-400">Versão: </span><span className="text-white">{resource.routerOsVersion}</span></div>
        <div><span className="text-gray-400">Plataforma: </span><span className="text-white">{resource.platform}</span></div>
        <div><span className="text-gray-400">Identidade: </span><span className="text-white">{resource.identity}</span></div>
      </div>
    </div>
  )
}

// src/app/components/system-resources/system-resources.component.ts
import { Component, Input, OnChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NgChartsModule } from 'ng2-charts';
import { ChartConfiguration, ChartData } from 'chart.js';
import { SystemResource, ChartPoint } from '../../models/netprobe.models';

@Component({
  selector: 'app-system-resources',
  standalone: true,
  imports: [CommonModule, NgChartsModule],
  templateUrl: './system-resources.component.html'
})
export class SystemResourcesComponent implements OnChanges {
  @Input() resource!: SystemResource;
  @Input() cpuHistory: ChartPoint[] = [];
  @Input() ramHistory: ChartPoint[] = [];

  cpuChartData: ChartData<'line'> = { labels: [], datasets: [] };
  ramChartData: ChartData<'line'> = { labels: [], datasets: [] };

  chartOptions: ChartConfiguration['options'] = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { ticks: { color: '#9ca3af', maxTicksLimit: 6 }, grid: { color: '#374151' } },
      y: { ticks: { color: '#9ca3af' }, grid: { color: '#374151' } }
    },
    elements: { point: { radius: 2 }, line: { tension: 0.3 } }
  };

  get usedMemMB(): number { return Math.round(this.resource.totalMemory - this.resource.freeMemory); }
  get usedDiskMB(): number { return Math.round(this.resource.totalDisk - this.resource.freeDisk); }
  get ramPercent(): number { return Math.round((this.usedMemMB / this.resource.totalMemory) * 100); }

  ngOnChanges(): void {
    this.cpuChartData = {
      labels: this.cpuHistory.map(p => p.timestamp),
      datasets: [{ data: this.cpuHistory.map(p => p.value), borderColor: '#3b82f6', backgroundColor: 'rgba(59,130,246,0.15)', fill: true, label: 'CPU %' }]
    };
    this.ramChartData = {
      labels: this.ramHistory.map(p => p.timestamp),
      datasets: [{ data: this.ramHistory.map(p => p.value), borderColor: '#a855f7', backgroundColor: 'rgba(168,85,247,0.15)', fill: true, label: 'RAM MB' }]
    };
  }
}

<div class="space-y-6">
  <!-- Cards -->
  <div class="grid grid-cols-2 lg:grid-cols-4 gap-4">
    <div class="bg-gray-800 border border-gray-700 rounded-xl p-5">
      <p class="text-xs text-gray-400 uppercase tracking-wide">CPU</p>
      <p class="text-3xl font-bold text-blue-400 mt-1">{{ resource.cpuLoad }}<span class="text-lg text-gray-400">%</span></p>
    </div>
    <div class="bg-gray-800 border border-gray-700 rounded-xl p-5">
      <p class="text-xs text-gray-400 uppercase tracking-wide">RAM usada</p>
      <p class="text-3xl font-bold text-purple-400 mt-1">{{ usedMemMB }}<span class="text-lg text-gray-400"> MB</span></p>
      <p class="text-xs text-gray-500 mt-1">{{ ramPercent }}% de {{ resource.totalMemory | number:'1.0-0' }} MB</p>
    </div>
    <div class="bg-gray-800 border border-gray-700 rounded-xl p-5">
      <p class="text-xs text-gray-400 uppercase tracking-wide">Disco usado</p>
      <p class="text-2xl font-bold text-emerald-400 mt-1">{{ usedDiskMB }}<span class="text-base text-gray-400"> MB</span></p>
      <p class="text-xs text-gray-500 mt-1">livre: {{ resource.freeDisk | number:'1.0-0' }} MB</p>
    </div>
    <div class="bg-gray-800 border border-gray-700 rounded-xl p-5">
      <p class="text-xs text-gray-400 uppercase tracking-wide">Uptime</p>
      <p class="text-lg font-semibold text-white mt-1 break-all">{{ resource.uptime }}</p>
    </div>
  </div>

  <!-- Gráficos -->
  <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
    <div class="bg-gray-800 border border-gray-700 rounded-xl p-5">
      <p class="text-sm text-gray-400 mb-3">CPU (%) — últimos 30 pontos</p>
      <div class="h-48">
        <canvas baseChart [data]="cpuChartData" [options]="chartOptions" type="line"></canvas>
      </div>
    </div>
    <div class="bg-gray-800 border border-gray-700 rounded-xl p-5">
      <p class="text-sm text-gray-400 mb-3">RAM (MB) — últimos 30 pontos</p>
      <div class="h-48">
        <canvas baseChart [data]="ramChartData" [options]="chartOptions" type="line"></canvas>
      </div>
    </div>
  </div>

  <!-- Info extra -->
  <div class="bg-gray-800 border border-gray-700 rounded-xl p-5 grid grid-cols-2 lg:grid-cols-3 gap-4 text-sm">
    <div><span class="text-gray-400">Versão: </span><span class="text-white">{{ resource.routerOsVersion }}</span></div>
    <div><span class="text-gray-400">Plataforma: </span><span class="text-white">{{ resource.platform }}</span></div>
    <div><span class="text-gray-400">Identidade: </span><span class="text-white">{{ resource.identity }}</span></div>
  </div>
</div>
